---
title: 'Week 6 Lecture Notebook 2: Visualizing How the Distribution of Sample Means Changes in Response to Changes in Sample Size'
output: html_document
runtime: shiny
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
```


```{r correlate, echo = FALSE}
mean_distribution = function(Sample_size){                 # Function to record mean values of samples                
    average_values=c()                                     # Vector to hold averagae values
    for (i in 1:1000){                                     # Take 1000 samples                                     
        faces=c(1,2,3,4,5,6)
        outcomes=(sample(faces, replace=TRUE, Sample_size))
        average_values=append(average_values, mean(outcomes)) # Compute average value for sample i
    }
    hist(average_values, freq=FALSE,xlim = c(1,6), ylim = c(0,2.5),
         xlab = "mean_dice_roll_outcomes", main = "Distribution of mean dice roll number") 
    # Draw distribution of mean values
}
inputPanel(
     sliderInput("num", label = "Sample Size: ",
              min = 1, max = 100, value = 15, step = 1),
)
renderPlot(mean_distribution(input$num))
```


